// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: input/proto/example/v1/common.proto

package examplev1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_input_proto_example_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_example_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_input_proto_example_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NestedIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedIds) Reset() {
	*x = NestedIds{}
	mi := &file_input_proto_example_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedIds) ProtoMessage() {}

func (x *NestedIds) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_example_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedIds.ProtoReflect.Descriptor instead.
func (*NestedIds) Descriptor() ([]byte, []int) {
	return file_input_proto_example_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *NestedIds) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NestedIds) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type NestedResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedIds     *NestedIds             `protobuf:"bytes,1,opt,name=nestedIds,proto3" json:"nestedIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedResource) Reset() {
	*x = NestedResource{}
	mi := &file_input_proto_example_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedResource) ProtoMessage() {}

func (x *NestedResource) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_example_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedResource.ProtoReflect.Descriptor instead.
func (*NestedResource) Descriptor() ([]byte, []int) {
	return file_input_proto_example_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *NestedResource) GetNestedIds() *NestedIds {
	if x != nil {
		return x.NestedIds
	}
	return nil
}

var File_input_proto_example_v1_common_proto protoreflect.FileDescriptor

const file_input_proto_example_v1_common_proto_rawDesc = "" +
	"\n" +
	"#input/proto/example/v1/common.proto\x12\n" +
	"example.v1\x1a\x1fnrf110/permify/v1/permify.proto\".\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\tNestedIds\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12#\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\tcompanyId\"Q\n" +
	"\x0eNestedResource\x123\n" +
	"\tnestedIds\x18\x01 \x01(\v2\x15.example.v1.NestedIdsR\tnestedIds:\n" +
	"»\x01\x06NestedBLZJgithub.com/example/example-service/output/input/proto/example/v1;examplev1b\x06proto3"

var (
	file_input_proto_example_v1_common_proto_rawDescOnce sync.Once
	file_input_proto_example_v1_common_proto_rawDescData []byte
)

func file_input_proto_example_v1_common_proto_rawDescGZIP() []byte {
	file_input_proto_example_v1_common_proto_rawDescOnce.Do(func() {
		file_input_proto_example_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_input_proto_example_v1_common_proto_rawDesc), len(file_input_proto_example_v1_common_proto_rawDesc)))
	})
	return file_input_proto_example_v1_common_proto_rawDescData
}

var file_input_proto_example_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_input_proto_example_v1_common_proto_goTypes = []any{
	(*Response)(nil),       // 0: example.v1.Response
	(*NestedIds)(nil),      // 1: example.v1.NestedIds
	(*NestedResource)(nil), // 2: example.v1.NestedResource
}
var file_input_proto_example_v1_common_proto_depIdxs = []int32{
	1, // 0: example.v1.NestedResource.nestedIds:type_name -> example.v1.NestedIds
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_input_proto_example_v1_common_proto_init() }
func file_input_proto_example_v1_common_proto_init() {
	if File_input_proto_example_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_input_proto_example_v1_common_proto_rawDesc), len(file_input_proto_example_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_input_proto_example_v1_common_proto_goTypes,
		DependencyIndexes: file_input_proto_example_v1_common_proto_depIdxs,
		MessageInfos:      file_input_proto_example_v1_common_proto_msgTypes,
	}.Build()
	File_input_proto_example_v1_common_proto = out.File
	file_input_proto_example_v1_common_proto_goTypes = nil
	file_input_proto_example_v1_common_proto_depIdxs = nil
}
