// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: input/proto/example/v1/public.proto

package examplev1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicRequest) Reset() {
	*x = PublicRequest{}
	mi := &file_input_proto_example_v1_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicRequest) ProtoMessage() {}

func (x *PublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_example_v1_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicRequest.ProtoReflect.Descriptor instead.
func (*PublicRequest) Descriptor() ([]byte, []int) {
	return file_input_proto_example_v1_public_proto_rawDescGZIP(), []int{0}
}

func (x *PublicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_input_proto_example_v1_public_proto protoreflect.FileDescriptor

const file_input_proto_example_v1_public_proto_rawDesc = "" +
	"\n" +
	"#input/proto/example/v1/public.proto\x12\n" +
	"example.v1\x1a#input/proto/example/v1/common.proto\x1a\x1fnrf110/permify/v1/permify.proto\"/\n" +
	"\rPublicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:\n" +
	"»\x01\x06Public2V\n" +
	"\x13OrganizationService\x12?\n" +
	"\x06Create\x12\x19.example.v1.PublicRequest\x1a\x14.example.v1.Response\"\x04Ȼ\x01\x01BLZJgithub.com/example/example-service/output/input/proto/example/v1;examplev1b\x06proto3"

var (
	file_input_proto_example_v1_public_proto_rawDescOnce sync.Once
	file_input_proto_example_v1_public_proto_rawDescData []byte
)

func file_input_proto_example_v1_public_proto_rawDescGZIP() []byte {
	file_input_proto_example_v1_public_proto_rawDescOnce.Do(func() {
		file_input_proto_example_v1_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_input_proto_example_v1_public_proto_rawDesc), len(file_input_proto_example_v1_public_proto_rawDesc)))
	})
	return file_input_proto_example_v1_public_proto_rawDescData
}

var file_input_proto_example_v1_public_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_input_proto_example_v1_public_proto_goTypes = []any{
	(*PublicRequest)(nil), // 0: example.v1.PublicRequest
	(*Response)(nil),      // 1: example.v1.Response
}
var file_input_proto_example_v1_public_proto_depIdxs = []int32{
	0, // 0: example.v1.OrganizationService.Create:input_type -> example.v1.PublicRequest
	1, // 1: example.v1.OrganizationService.Create:output_type -> example.v1.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_input_proto_example_v1_public_proto_init() }
func file_input_proto_example_v1_public_proto_init() {
	if File_input_proto_example_v1_public_proto != nil {
		return
	}
	file_input_proto_example_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_input_proto_example_v1_public_proto_rawDesc), len(file_input_proto_example_v1_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_input_proto_example_v1_public_proto_goTypes,
		DependencyIndexes: file_input_proto_example_v1_public_proto_depIdxs,
		MessageInfos:      file_input_proto_example_v1_public_proto_msgTypes,
	}.Build()
	File_input_proto_example_v1_public_proto = out.File
	file_input_proto_example_v1_public_proto_goTypes = nil
	file_input_proto_example_v1_public_proto_depIdxs = nil
}
