// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: input/proto/example/v1/attributes.proto

package examplev1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/example/example-service/output/input/proto/example/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AttributesName is the fully-qualified name of the Attributes service.
	AttributesName = "example.v1.Attributes"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AttributesWithAttributesProcedure is the fully-qualified name of the Attributes's WithAttributes
	// RPC.
	AttributesWithAttributesProcedure = "/example.v1.Attributes/WithAttributes"
)

// AttributesClient is a client for the example.v1.Attributes service.
type AttributesClient interface {
	WithAttributes(context.Context, *connect_go.Request[v1.AttributesRequest]) (*connect_go.Response[v1.Response], error)
}

// NewAttributesClient constructs a client for the example.v1.Attributes service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAttributesClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AttributesClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &attributesClient{
		withAttributes: connect_go.NewClient[v1.AttributesRequest, v1.Response](
			httpClient,
			baseURL+AttributesWithAttributesProcedure,
			opts...,
		),
	}
}

// attributesClient implements AttributesClient.
type attributesClient struct {
	withAttributes *connect_go.Client[v1.AttributesRequest, v1.Response]
}

// WithAttributes calls example.v1.Attributes.WithAttributes.
func (c *attributesClient) WithAttributes(ctx context.Context, req *connect_go.Request[v1.AttributesRequest]) (*connect_go.Response[v1.Response], error) {
	return c.withAttributes.CallUnary(ctx, req)
}

// AttributesHandler is an implementation of the example.v1.Attributes service.
type AttributesHandler interface {
	WithAttributes(context.Context, *connect_go.Request[v1.AttributesRequest]) (*connect_go.Response[v1.Response], error)
}

// NewAttributesHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAttributesHandler(svc AttributesHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	attributesWithAttributesHandler := connect_go.NewUnaryHandler(
		AttributesWithAttributesProcedure,
		svc.WithAttributes,
		opts...,
	)
	return "/example.v1.Attributes/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AttributesWithAttributesProcedure:
			attributesWithAttributesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAttributesHandler returns CodeUnimplemented from all methods.
type UnimplementedAttributesHandler struct{}

func (UnimplementedAttributesHandler) WithAttributes(context.Context, *connect_go.Request[v1.AttributesRequest]) (*connect_go.Response[v1.Response], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("example.v1.Attributes.WithAttributes is not implemented"))
}
