// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: test/v1/multiple_resources.proto

package testv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
	v1 "test/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// MultiResourceServiceName is the fully-qualified name of the MultiResourceService service.
	MultiResourceServiceName = "test.v1.MultiResourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MultiResourceServiceProcessMultipleResourcesProcedure is the fully-qualified name of the
	// MultiResourceService's ProcessMultipleResources RPC.
	MultiResourceServiceProcessMultipleResourcesProcedure = "/test.v1.MultiResourceService/ProcessMultipleResources"
)

// MultiResourceServiceClient is a client for the test.v1.MultiResourceService service.
type MultiResourceServiceClient interface {
	ProcessMultipleResources(context.Context, *connect_go.Request[v1.MultiResourceRequest]) (*connect_go.Response[v1.Response], error)
}

// NewMultiResourceServiceClient constructs a client for the test.v1.MultiResourceService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMultiResourceServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) MultiResourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &multiResourceServiceClient{
		processMultipleResources: connect_go.NewClient[v1.MultiResourceRequest, v1.Response](
			httpClient,
			baseURL+MultiResourceServiceProcessMultipleResourcesProcedure,
			opts...,
		),
	}
}

// multiResourceServiceClient implements MultiResourceServiceClient.
type multiResourceServiceClient struct {
	processMultipleResources *connect_go.Client[v1.MultiResourceRequest, v1.Response]
}

// ProcessMultipleResources calls test.v1.MultiResourceService.ProcessMultipleResources.
func (c *multiResourceServiceClient) ProcessMultipleResources(ctx context.Context, req *connect_go.Request[v1.MultiResourceRequest]) (*connect_go.Response[v1.Response], error) {
	return c.processMultipleResources.CallUnary(ctx, req)
}

// MultiResourceServiceHandler is an implementation of the test.v1.MultiResourceService service.
type MultiResourceServiceHandler interface {
	ProcessMultipleResources(context.Context, *connect_go.Request[v1.MultiResourceRequest]) (*connect_go.Response[v1.Response], error)
}

// NewMultiResourceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMultiResourceServiceHandler(svc MultiResourceServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	multiResourceServiceProcessMultipleResourcesHandler := connect_go.NewUnaryHandler(
		MultiResourceServiceProcessMultipleResourcesProcedure,
		svc.ProcessMultipleResources,
		opts...,
	)
	return "/test.v1.MultiResourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MultiResourceServiceProcessMultipleResourcesProcedure:
			multiResourceServiceProcessMultipleResourcesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMultiResourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMultiResourceServiceHandler struct{}

func (UnimplementedMultiResourceServiceHandler) ProcessMultipleResources(context.Context, *connect_go.Request[v1.MultiResourceRequest]) (*connect_go.Response[v1.Response], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("test.v1.MultiResourceService.ProcessMultipleResources is not implemented"))
}
