// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: test/v1/nested_resources.proto

package testv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "test/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NestedServiceName is the fully-qualified name of the NestedService service.
	NestedServiceName = "test.v1.NestedService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NestedServiceProcessNestedProcedure is the fully-qualified name of the NestedService's
	// ProcessNested RPC.
	NestedServiceProcessNestedProcedure = "/test.v1.NestedService/ProcessNested"
)

// NestedServiceClient is a client for the test.v1.NestedService service.
type NestedServiceClient interface {
	ProcessNested(context.Context, *connect.Request[v1.NestedRequest]) (*connect.Response[v1.Response], error)
}

// NewNestedServiceClient constructs a client for the test.v1.NestedService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNestedServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NestedServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nestedServiceMethods := v1.File_test_v1_nested_resources_proto.Services().ByName("NestedService").Methods()
	return &nestedServiceClient{
		processNested: connect.NewClient[v1.NestedRequest, v1.Response](
			httpClient,
			baseURL+NestedServiceProcessNestedProcedure,
			connect.WithSchema(nestedServiceMethods.ByName("ProcessNested")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nestedServiceClient implements NestedServiceClient.
type nestedServiceClient struct {
	processNested *connect.Client[v1.NestedRequest, v1.Response]
}

// ProcessNested calls test.v1.NestedService.ProcessNested.
func (c *nestedServiceClient) ProcessNested(ctx context.Context, req *connect.Request[v1.NestedRequest]) (*connect.Response[v1.Response], error) {
	return c.processNested.CallUnary(ctx, req)
}

// NestedServiceHandler is an implementation of the test.v1.NestedService service.
type NestedServiceHandler interface {
	ProcessNested(context.Context, *connect.Request[v1.NestedRequest]) (*connect.Response[v1.Response], error)
}

// NewNestedServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNestedServiceHandler(svc NestedServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nestedServiceMethods := v1.File_test_v1_nested_resources_proto.Services().ByName("NestedService").Methods()
	nestedServiceProcessNestedHandler := connect.NewUnaryHandler(
		NestedServiceProcessNestedProcedure,
		svc.ProcessNested,
		connect.WithSchema(nestedServiceMethods.ByName("ProcessNested")),
		connect.WithHandlerOptions(opts...),
	)
	return "/test.v1.NestedService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NestedServiceProcessNestedProcedure:
			nestedServiceProcessNestedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNestedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNestedServiceHandler struct{}

func (UnimplementedNestedServiceHandler) ProcessNested(context.Context, *connect.Request[v1.NestedRequest]) (*connect.Response[v1.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("test.v1.NestedService.ProcessNested is not implemented"))
}
