// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: test/v1/attributes.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           string                 `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedAttribute) Reset() {
	*x = NestedAttribute{}
	mi := &file_test_v1_attributes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedAttribute) ProtoMessage() {}

func (x *NestedAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_attributes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedAttribute.ProtoReflect.Descriptor instead.
func (*NestedAttribute) Descriptor() ([]byte, []int) {
	return file_test_v1_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *NestedAttribute) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

type MappedAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bar           string                 `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappedAttribute) Reset() {
	*x = MappedAttribute{}
	mi := &file_test_v1_attributes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedAttribute) ProtoMessage() {}

func (x *MappedAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_attributes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedAttribute.ProtoReflect.Descriptor instead.
func (*MappedAttribute) Descriptor() ([]byte, []int) {
	return file_test_v1_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *MappedAttribute) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

type ComplexAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blah          []string               `protobuf:"bytes,1,rep,name=blah,proto3" json:"blah,omitempty"`
	Blar          float64                `protobuf:"fixed64,2,opt,name=blar,proto3" json:"blar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexAttribute) Reset() {
	*x = ComplexAttribute{}
	mi := &file_test_v1_attributes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexAttribute) ProtoMessage() {}

func (x *ComplexAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_attributes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexAttribute.ProtoReflect.Descriptor instead.
func (*ComplexAttribute) Descriptor() ([]byte, []int) {
	return file_test_v1_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *ComplexAttribute) GetBlah() []string {
	if x != nil {
		return x.Blah
	}
	return nil
}

func (x *ComplexAttribute) GetBlar() float64 {
	if x != nil {
		return x.Blar
	}
	return 0
}

type AttributesRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Complex       []*ComplexAttribute         `protobuf:"bytes,1,rep,name=complex,proto3" json:"complex,omitempty"`
	Nested        []*NestedAttribute          `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	Mapped        map[string]*MappedAttribute `protobuf:"bytes,3,rep,name=mapped,proto3" json:"mapped,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Id            string                      `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                      `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributesRequest) Reset() {
	*x = AttributesRequest{}
	mi := &file_test_v1_attributes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesRequest) ProtoMessage() {}

func (x *AttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_attributes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesRequest.ProtoReflect.Descriptor instead.
func (*AttributesRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_attributes_proto_rawDescGZIP(), []int{3}
}

func (x *AttributesRequest) GetComplex() []*ComplexAttribute {
	if x != nil {
		return x.Complex
	}
	return nil
}

func (x *AttributesRequest) GetNested() []*NestedAttribute {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *AttributesRequest) GetMapped() map[string]*MappedAttribute {
	if x != nil {
		return x.Mapped
	}
	return nil
}

func (x *AttributesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

var File_test_v1_attributes_proto protoreflect.FileDescriptor

const file_test_v1_attributes_proto_rawDesc = "" +
	"\n" +
	"\x18test/v1/attributes.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\",\n" +
	"\x0fNestedAttribute\x12\x19\n" +
	"\x03foo\x18\x01 \x01(\tB\aһ\x01\x03fooR\x03foo\",\n" +
	"\x0fMappedAttribute\x12\x19\n" +
	"\x03bar\x18\x01 \x01(\tB\aһ\x01\x03fooR\x03bar\":\n" +
	"\x10ComplexAttribute\x12\x12\n" +
	"\x04blah\x18\x01 \x03(\tR\x04blah\x12\x12\n" +
	"\x04blar\x18\x02 \x01(\x01R\x04blar\"\xe7\x02\n" +
	"\x11AttributesRequest\x12@\n" +
	"\acomplex\x18\x01 \x03(\v2\x19.test.v1.ComplexAttributeB\vһ\x01\acomplexR\acomplex\x120\n" +
	"\x06nested\x18\x02 \x03(\v2\x18.test.v1.NestedAttributeR\x06nested\x12>\n" +
	"\x06mapped\x18\x03 \x03(\v2&.test.v1.AttributesRequest.MappedEntryR\x06mapped\x12\x14\n" +
	"\x02id\x18\x04 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12#\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tB\x04Ȼ\x01\x01R\tcompanyId\x1aS\n" +
	"\vMappedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.test.v1.MappedAttributeR\x05value:\x028\x01:\x0e»\x01\n" +
	"Attributes2W\n" +
	"\n" +
	"Attributes\x12I\n" +
	"\x0eWithAttributes\x12\x1a.test.v1.AttributesRequest\x1a\x11.test.v1.Response\"\b»\x01\x04readB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_attributes_proto_rawDescOnce sync.Once
	file_test_v1_attributes_proto_rawDescData []byte
)

func file_test_v1_attributes_proto_rawDescGZIP() []byte {
	file_test_v1_attributes_proto_rawDescOnce.Do(func() {
		file_test_v1_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_attributes_proto_rawDesc), len(file_test_v1_attributes_proto_rawDesc)))
	})
	return file_test_v1_attributes_proto_rawDescData
}

var file_test_v1_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_v1_attributes_proto_goTypes = []any{
	(*NestedAttribute)(nil),   // 0: test.v1.NestedAttribute
	(*MappedAttribute)(nil),   // 1: test.v1.MappedAttribute
	(*ComplexAttribute)(nil),  // 2: test.v1.ComplexAttribute
	(*AttributesRequest)(nil), // 3: test.v1.AttributesRequest
	nil,                       // 4: test.v1.AttributesRequest.MappedEntry
	(*Response)(nil),          // 5: test.v1.Response
}
var file_test_v1_attributes_proto_depIdxs = []int32{
	2, // 0: test.v1.AttributesRequest.complex:type_name -> test.v1.ComplexAttribute
	0, // 1: test.v1.AttributesRequest.nested:type_name -> test.v1.NestedAttribute
	4, // 2: test.v1.AttributesRequest.mapped:type_name -> test.v1.AttributesRequest.MappedEntry
	1, // 3: test.v1.AttributesRequest.MappedEntry.value:type_name -> test.v1.MappedAttribute
	3, // 4: test.v1.Attributes.WithAttributes:input_type -> test.v1.AttributesRequest
	5, // 5: test.v1.Attributes.WithAttributes:output_type -> test.v1.Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_test_v1_attributes_proto_init() }
func file_test_v1_attributes_proto_init() {
	if File_test_v1_attributes_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_attributes_proto_rawDesc), len(file_test_v1_attributes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_attributes_proto_goTypes,
		DependencyIndexes: file_test_v1_attributes_proto_depIdxs,
		MessageInfos:      file_test_v1_attributes_proto_msgTypes,
	}.Build()
	File_test_v1_attributes_proto = out.File
	file_test_v1_attributes_proto_goTypes = nil
	file_test_v1_attributes_proto_depIdxs = nil
}
