// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/v1/complex_attributes.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeData) Reset() {
	*x = AttributeData{}
	mi := &file_test_v1_complex_attributes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeData) ProtoMessage() {}

func (x *AttributeData) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_complex_attributes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeData.ProtoReflect.Descriptor instead.
func (*AttributeData) Descriptor() ([]byte, []int) {
	return file_test_v1_complex_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AttributeData) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ComplexResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Attributes    []*AttributeData       `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Department    string                 `protobuf:"bytes,5,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexResource) Reset() {
	*x = ComplexResource{}
	mi := &file_test_v1_complex_attributes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexResource) ProtoMessage() {}

func (x *ComplexResource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_complex_attributes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexResource.ProtoReflect.Descriptor instead.
func (*ComplexResource) Descriptor() ([]byte, []int) {
	return file_test_v1_complex_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *ComplexResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComplexResource) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ComplexResource) GetAttributes() []*AttributeData {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ComplexResource) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ComplexResource) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

var File_test_v1_complex_attributes_proto protoreflect.FileDescriptor

const file_test_v1_complex_attributes_proto_rawDesc = "" +
	"\n" +
	" test/v1/complex_attributes.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"c\n" +
	"\rAttributeData\x12(\n" +
	"\bcategory\x18\x01 \x01(\tB\fһ\x01\bcategoryR\bcategory\x12(\n" +
	"\bpriority\x18\x02 \x01(\x05B\fһ\x01\bpriorityR\bpriority\"\xbb\x02\n" +
	"\x0fComplexResource\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12!\n" +
	"\ttenant_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\btenantId\x126\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x16.test.v1.AttributeDataR\n" +
	"attributes\x12@\n" +
	"\x04tags\x18\x04 \x03(\v2\".test.v1.ComplexResource.TagsEntryB\bһ\x01\x04tagsR\x04tags\x12.\n" +
	"\n" +
	"department\x18\x05 \x01(\tB\x0eһ\x01\n" +
	"departmentR\n" +
	"department\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\f»\x01\bDocument2_\n" +
	"\x10AttributeService\x12K\n" +
	"\x0fProcessDocument\x12\x18.test.v1.ComplexResource\x1a\x11.test.v1.Response\"\v»\x01\aprocessB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_complex_attributes_proto_rawDescOnce sync.Once
	file_test_v1_complex_attributes_proto_rawDescData []byte
)

func file_test_v1_complex_attributes_proto_rawDescGZIP() []byte {
	file_test_v1_complex_attributes_proto_rawDescOnce.Do(func() {
		file_test_v1_complex_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_complex_attributes_proto_rawDesc), len(file_test_v1_complex_attributes_proto_rawDesc)))
	})
	return file_test_v1_complex_attributes_proto_rawDescData
}

var file_test_v1_complex_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_v1_complex_attributes_proto_goTypes = []any{
	(*AttributeData)(nil),   // 0: test.v1.AttributeData
	(*ComplexResource)(nil), // 1: test.v1.ComplexResource
	nil,                     // 2: test.v1.ComplexResource.TagsEntry
	(*Response)(nil),        // 3: test.v1.Response
}
var file_test_v1_complex_attributes_proto_depIdxs = []int32{
	0, // 0: test.v1.ComplexResource.attributes:type_name -> test.v1.AttributeData
	2, // 1: test.v1.ComplexResource.tags:type_name -> test.v1.ComplexResource.TagsEntry
	1, // 2: test.v1.AttributeService.ProcessDocument:input_type -> test.v1.ComplexResource
	3, // 3: test.v1.AttributeService.ProcessDocument:output_type -> test.v1.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_v1_complex_attributes_proto_init() }
func file_test_v1_complex_attributes_proto_init() {
	if File_test_v1_complex_attributes_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_complex_attributes_proto_rawDesc), len(file_test_v1_complex_attributes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_complex_attributes_proto_goTypes,
		DependencyIndexes: file_test_v1_complex_attributes_proto_depIdxs,
		MessageInfos:      file_test_v1_complex_attributes_proto_msgTypes,
	}.Build()
	File_test_v1_complex_attributes_proto = out.File
	file_test_v1_complex_attributes_proto_goTypes = nil
	file_test_v1_complex_attributes_proto_depIdxs = nil
}
