// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/v1/deep_nesting.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level3Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level3Resource) Reset() {
	*x = Level3Resource{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level3Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level3Resource) ProtoMessage() {}

func (x *Level3Resource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level3Resource.ProtoReflect.Descriptor instead.
func (*Level3Resource) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{0}
}

func (x *Level3Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Level3Resource) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Level2Container struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Resource      *Level3Resource            `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourcesMap  map[string]*Level3Resource `protobuf:"bytes,2,rep,name=resources_map,json=resourcesMap,proto3" json:"resources_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourcesList []*Level3Resource          `protobuf:"bytes,3,rep,name=resources_list,json=resourcesList,proto3" json:"resources_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level2Container) Reset() {
	*x = Level2Container{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level2Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level2Container) ProtoMessage() {}

func (x *Level2Container) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level2Container.ProtoReflect.Descriptor instead.
func (*Level2Container) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{1}
}

func (x *Level2Container) GetResource() *Level3Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Level2Container) GetResourcesMap() map[string]*Level3Resource {
	if x != nil {
		return x.ResourcesMap
	}
	return nil
}

func (x *Level2Container) GetResourcesList() []*Level3Resource {
	if x != nil {
		return x.ResourcesList
	}
	return nil
}

type Level1Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level2        *Level2Container       `protobuf:"bytes,1,opt,name=level2,proto3" json:"level2,omitempty"`
	Level2List    []*Level2Container     `protobuf:"bytes,2,rep,name=level2_list,json=level2List,proto3" json:"level2_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level1Container) Reset() {
	*x = Level1Container{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level1Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level1Container) ProtoMessage() {}

func (x *Level1Container) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level1Container.ProtoReflect.Descriptor instead.
func (*Level1Container) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{2}
}

func (x *Level1Container) GetLevel2() *Level2Container {
	if x != nil {
		return x.Level2
	}
	return nil
}

func (x *Level1Container) GetLevel2List() []*Level2Container {
	if x != nil {
		return x.Level2List
	}
	return nil
}

type DeepNestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Level1Container       `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNestedRequest) Reset() {
	*x = DeepNestedRequest{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNestedRequest) ProtoMessage() {}

func (x *DeepNestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNestedRequest.ProtoReflect.Descriptor instead.
func (*DeepNestedRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{3}
}

func (x *DeepNestedRequest) GetContainer() *Level1Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *DeepNestedRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type VeryDeepIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeepId        string                 `protobuf:"bytes,1,opt,name=deep_id,json=deepId,proto3" json:"deep_id,omitempty"`
	DeepTenant    string                 `protobuf:"bytes,2,opt,name=deep_tenant,json=deepTenant,proto3" json:"deep_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeryDeepIds) Reset() {
	*x = VeryDeepIds{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeryDeepIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeryDeepIds) ProtoMessage() {}

func (x *VeryDeepIds) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeryDeepIds.ProtoReflect.Descriptor instead.
func (*VeryDeepIds) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{4}
}

func (x *VeryDeepIds) GetDeepId() string {
	if x != nil {
		return x.DeepId
	}
	return ""
}

func (x *VeryDeepIds) GetDeepTenant() string {
	if x != nil {
		return x.DeepTenant
	}
	return ""
}

type VeryDeepLevel3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           *VeryDeepIds           `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeryDeepLevel3) Reset() {
	*x = VeryDeepLevel3{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeryDeepLevel3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeryDeepLevel3) ProtoMessage() {}

func (x *VeryDeepLevel3) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeryDeepLevel3.ProtoReflect.Descriptor instead.
func (*VeryDeepLevel3) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{5}
}

func (x *VeryDeepLevel3) GetIds() *VeryDeepIds {
	if x != nil {
		return x.Ids
	}
	return nil
}

type VeryDeepLevel2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level3        *VeryDeepLevel3        `protobuf:"bytes,1,opt,name=level3,proto3" json:"level3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeryDeepLevel2) Reset() {
	*x = VeryDeepLevel2{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeryDeepLevel2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeryDeepLevel2) ProtoMessage() {}

func (x *VeryDeepLevel2) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeryDeepLevel2.ProtoReflect.Descriptor instead.
func (*VeryDeepLevel2) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{6}
}

func (x *VeryDeepLevel2) GetLevel3() *VeryDeepLevel3 {
	if x != nil {
		return x.Level3
	}
	return nil
}

type VeryDeepLevel1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level2        *VeryDeepLevel2        `protobuf:"bytes,1,opt,name=level2,proto3" json:"level2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeryDeepLevel1) Reset() {
	*x = VeryDeepLevel1{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeryDeepLevel1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeryDeepLevel1) ProtoMessage() {}

func (x *VeryDeepLevel1) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeryDeepLevel1.ProtoReflect.Descriptor instead.
func (*VeryDeepLevel1) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{7}
}

func (x *VeryDeepLevel1) GetLevel2() *VeryDeepLevel2 {
	if x != nil {
		return x.Level2
	}
	return nil
}

type VeryDeepResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level1        *VeryDeepLevel1        `protobuf:"bytes,1,opt,name=level1,proto3" json:"level1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeryDeepResource) Reset() {
	*x = VeryDeepResource{}
	mi := &file_test_v1_deep_nesting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeryDeepResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeryDeepResource) ProtoMessage() {}

func (x *VeryDeepResource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_deep_nesting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeryDeepResource.ProtoReflect.Descriptor instead.
func (*VeryDeepResource) Descriptor() ([]byte, []int) {
	return file_test_v1_deep_nesting_proto_rawDescGZIP(), []int{8}
}

func (x *VeryDeepResource) GetLevel1() *VeryDeepLevel1 {
	if x != nil {
		return x.Level1
	}
	return nil
}

var File_test_v1_deep_nesting_proto protoreflect.FileDescriptor

const file_test_v1_deep_nesting_proto_rawDesc = "" +
	"\n" +
	"\x1atest/v1/deep_nesting.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"W\n" +
	"\x0eLevel3Resource\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12#\n" +
	"\x04data\x18\x02 \x01(\tB\x0fһ\x01\vlevel3_dataR\x04data:\n" +
	"»\x01\x06Level3\"\xb1\x02\n" +
	"\x0fLevel2Container\x123\n" +
	"\bresource\x18\x01 \x01(\v2\x17.test.v1.Level3ResourceR\bresource\x12O\n" +
	"\rresources_map\x18\x02 \x03(\v2*.test.v1.Level2Container.ResourcesMapEntryR\fresourcesMap\x12>\n" +
	"\x0eresources_list\x18\x03 \x03(\v2\x17.test.v1.Level3ResourceR\rresourcesList\x1aX\n" +
	"\x11ResourcesMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.test.v1.Level3ResourceR\x05value:\x028\x01\"~\n" +
	"\x0fLevel1Container\x120\n" +
	"\x06level2\x18\x01 \x01(\v2\x18.test.v1.Level2ContainerR\x06level2\x129\n" +
	"\vlevel2_list\x18\x02 \x03(\v2\x18.test.v1.Level2ContainerR\n" +
	"level2List\"g\n" +
	"\x11DeepNestedRequest\x126\n" +
	"\tcontainer\x18\x01 \x01(\v2\x18.test.v1.Level1ContainerR\tcontainer\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"S\n" +
	"\vVeryDeepIds\x12\x1d\n" +
	"\adeep_id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x06deepId\x12%\n" +
	"\vdeep_tenant\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\n" +
	"deepTenant\"8\n" +
	"\x0eVeryDeepLevel3\x12&\n" +
	"\x03ids\x18\x01 \x01(\v2\x14.test.v1.VeryDeepIdsR\x03ids\"A\n" +
	"\x0eVeryDeepLevel2\x12/\n" +
	"\x06level3\x18\x01 \x01(\v2\x17.test.v1.VeryDeepLevel3R\x06level3\"A\n" +
	"\x0eVeryDeepLevel1\x12/\n" +
	"\x06level2\x18\x01 \x01(\v2\x17.test.v1.VeryDeepLevel2R\x06level2\"Q\n" +
	"\x10VeryDeepResource\x12/\n" +
	"\x06level1\x18\x01 \x01(\v2\x17.test.v1.VeryDeepLevel1R\x06level1:\f»\x01\bVeryDeep2\xb1\x01\n" +
	"\x12DeepNestingService\x12O\n" +
	"\x11ProcessDeepNested\x12\x1a.test.v1.DeepNestedRequest\x1a\x11.test.v1.Response\"\v»\x01\aprocess\x12J\n" +
	"\x0fProcessVeryDeep\x12\x19.test.v1.VeryDeepResource\x1a\x11.test.v1.Response\"\t»\x01\x05adminB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_deep_nesting_proto_rawDescOnce sync.Once
	file_test_v1_deep_nesting_proto_rawDescData []byte
)

func file_test_v1_deep_nesting_proto_rawDescGZIP() []byte {
	file_test_v1_deep_nesting_proto_rawDescOnce.Do(func() {
		file_test_v1_deep_nesting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_deep_nesting_proto_rawDesc), len(file_test_v1_deep_nesting_proto_rawDesc)))
	})
	return file_test_v1_deep_nesting_proto_rawDescData
}

var file_test_v1_deep_nesting_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_test_v1_deep_nesting_proto_goTypes = []any{
	(*Level3Resource)(nil),    // 0: test.v1.Level3Resource
	(*Level2Container)(nil),   // 1: test.v1.Level2Container
	(*Level1Container)(nil),   // 2: test.v1.Level1Container
	(*DeepNestedRequest)(nil), // 3: test.v1.DeepNestedRequest
	(*VeryDeepIds)(nil),       // 4: test.v1.VeryDeepIds
	(*VeryDeepLevel3)(nil),    // 5: test.v1.VeryDeepLevel3
	(*VeryDeepLevel2)(nil),    // 6: test.v1.VeryDeepLevel2
	(*VeryDeepLevel1)(nil),    // 7: test.v1.VeryDeepLevel1
	(*VeryDeepResource)(nil),  // 8: test.v1.VeryDeepResource
	nil,                       // 9: test.v1.Level2Container.ResourcesMapEntry
	(*Response)(nil),          // 10: test.v1.Response
}
var file_test_v1_deep_nesting_proto_depIdxs = []int32{
	0,  // 0: test.v1.Level2Container.resource:type_name -> test.v1.Level3Resource
	9,  // 1: test.v1.Level2Container.resources_map:type_name -> test.v1.Level2Container.ResourcesMapEntry
	0,  // 2: test.v1.Level2Container.resources_list:type_name -> test.v1.Level3Resource
	1,  // 3: test.v1.Level1Container.level2:type_name -> test.v1.Level2Container
	1,  // 4: test.v1.Level1Container.level2_list:type_name -> test.v1.Level2Container
	2,  // 5: test.v1.DeepNestedRequest.container:type_name -> test.v1.Level1Container
	4,  // 6: test.v1.VeryDeepLevel3.ids:type_name -> test.v1.VeryDeepIds
	5,  // 7: test.v1.VeryDeepLevel2.level3:type_name -> test.v1.VeryDeepLevel3
	6,  // 8: test.v1.VeryDeepLevel1.level2:type_name -> test.v1.VeryDeepLevel2
	7,  // 9: test.v1.VeryDeepResource.level1:type_name -> test.v1.VeryDeepLevel1
	0,  // 10: test.v1.Level2Container.ResourcesMapEntry.value:type_name -> test.v1.Level3Resource
	3,  // 11: test.v1.DeepNestingService.ProcessDeepNested:input_type -> test.v1.DeepNestedRequest
	8,  // 12: test.v1.DeepNestingService.ProcessVeryDeep:input_type -> test.v1.VeryDeepResource
	10, // 13: test.v1.DeepNestingService.ProcessDeepNested:output_type -> test.v1.Response
	10, // 14: test.v1.DeepNestingService.ProcessVeryDeep:output_type -> test.v1.Response
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_test_v1_deep_nesting_proto_init() }
func file_test_v1_deep_nesting_proto_init() {
	if File_test_v1_deep_nesting_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_deep_nesting_proto_rawDesc), len(file_test_v1_deep_nesting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_deep_nesting_proto_goTypes,
		DependencyIndexes: file_test_v1_deep_nesting_proto_depIdxs,
		MessageInfos:      file_test_v1_deep_nesting_proto_msgTypes,
	}.Build()
	File_test_v1_deep_nesting_proto = out.File
	file_test_v1_deep_nesting_proto_goTypes = nil
	file_test_v1_deep_nesting_proto_depIdxs = nil
}
