// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/v1/edge_cases.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_test_v1_edge_cases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_edge_cases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_edge_cases_proto_rawDescGZIP(), []int{0}
}

type MinimalResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinimalResource) Reset() {
	*x = MinimalResource{}
	mi := &file_test_v1_edge_cases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinimalResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalResource) ProtoMessage() {}

func (x *MinimalResource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_edge_cases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalResource.ProtoReflect.Descriptor instead.
func (*MinimalResource) Descriptor() ([]byte, []int) {
	return file_test_v1_edge_cases_proto_rawDescGZIP(), []int{1}
}

func (x *MinimalResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_test_v1_edge_cases_proto protoreflect.FileDescriptor

const file_test_v1_edge_cases_proto_rawDesc = "" +
	"\n" +
	"\x18test/v1/edge_cases.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"\x0e\n" +
	"\fEmptyRequest\"4\n" +
	"\x0fMinimalResource\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id:\v»\x01\aMinimal2\x0e\n" +
	"\fEmptyService2\x97\x01\n" +
	"\x10AllPublicService\x12?\n" +
	"\rPublicMethod1\x12\x15.test.v1.EmptyRequest\x1a\x11.test.v1.Response\"\x04Ȼ\x01\x01\x12B\n" +
	"\rPublicMethod2\x12\x18.test.v1.MinimalResource\x1a\x11.test.v1.Response\"\x04Ȼ\x01\x01B\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_edge_cases_proto_rawDescOnce sync.Once
	file_test_v1_edge_cases_proto_rawDescData []byte
)

func file_test_v1_edge_cases_proto_rawDescGZIP() []byte {
	file_test_v1_edge_cases_proto_rawDescOnce.Do(func() {
		file_test_v1_edge_cases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_edge_cases_proto_rawDesc), len(file_test_v1_edge_cases_proto_rawDesc)))
	})
	return file_test_v1_edge_cases_proto_rawDescData
}

var file_test_v1_edge_cases_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_v1_edge_cases_proto_goTypes = []any{
	(*EmptyRequest)(nil),    // 0: test.v1.EmptyRequest
	(*MinimalResource)(nil), // 1: test.v1.MinimalResource
	(*Response)(nil),        // 2: test.v1.Response
}
var file_test_v1_edge_cases_proto_depIdxs = []int32{
	0, // 0: test.v1.AllPublicService.PublicMethod1:input_type -> test.v1.EmptyRequest
	1, // 1: test.v1.AllPublicService.PublicMethod2:input_type -> test.v1.MinimalResource
	2, // 2: test.v1.AllPublicService.PublicMethod1:output_type -> test.v1.Response
	2, // 3: test.v1.AllPublicService.PublicMethod2:output_type -> test.v1.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_v1_edge_cases_proto_init() }
func file_test_v1_edge_cases_proto_init() {
	if File_test_v1_edge_cases_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_edge_cases_proto_rawDesc), len(file_test_v1_edge_cases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_v1_edge_cases_proto_goTypes,
		DependencyIndexes: file_test_v1_edge_cases_proto_depIdxs,
		MessageInfos:      file_test_v1_edge_cases_proto_msgTypes,
	}.Build()
	File_test_v1_edge_cases_proto = out.File
	file_test_v1_edge_cases_proto_goTypes = nil
	file_test_v1_edge_cases_proto_depIdxs = nil
}
