// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/v1/mixed_service.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRequest) Reset() {
	*x = SimpleRequest{}
	mi := &file_test_v1_mixed_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRequest) ProtoMessage() {}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_mixed_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRequest.ProtoReflect.Descriptor instead.
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_mixed_service_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetUserResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResource) Reset() {
	*x = GetUserResource{}
	mi := &file_test_v1_mixed_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResource) ProtoMessage() {}

func (x *GetUserResource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_mixed_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResource.ProtoReflect.Descriptor instead.
func (*GetUserResource) Descriptor() ([]byte, []int) {
	return file_test_v1_mixed_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResource) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResource) Reset() {
	*x = UpdateUserResource{}
	mi := &file_test_v1_mixed_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResource) ProtoMessage() {}

func (x *UpdateUserResource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_mixed_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResource.ProtoReflect.Descriptor instead.
func (*UpdateUserResource) Descriptor() ([]byte, []int) {
	return file_test_v1_mixed_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserResource) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserResource) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UpdateUserResource) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserResource) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DeleteUserResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResource) Reset() {
	*x = DeleteUserResource{}
	mi := &file_test_v1_mixed_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResource) ProtoMessage() {}

func (x *DeleteUserResource) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_mixed_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResource.ProtoReflect.Descriptor instead.
func (*DeleteUserResource) Descriptor() ([]byte, []int) {
	return file_test_v1_mixed_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserResource) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_test_v1_mixed_service_proto protoreflect.FileDescriptor

const file_test_v1_mixed_service_proto_rawDesc = "" +
	"\n" +
	"\x1btest/v1/mixed_service.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"%\n" +
	"\rSimpleRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\":\n" +
	"\x0fGetUserResource\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x06userId:\b»\x01\x04User\"\xa1\x01\n" +
	"\x12UpdateUserResource\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x06userId\x12#\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\tcompanyId\x12\x1f\n" +
	"\x05email\x18\x03 \x01(\tB\tһ\x01\x05emailR\x05email\x12\x1c\n" +
	"\x04role\x18\x04 \x01(\tB\bһ\x01\x04roleR\x04role:\b»\x01\x04User\"=\n" +
	"\x12DeleteUserResource\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x06userId:\b»\x01\x04User2\xa4\x02\n" +
	"\fMixedService\x12@\n" +
	"\rGetPublicInfo\x12\x16.test.v1.SimpleRequest\x1a\x11.test.v1.Response\"\x04Ȼ\x01\x01\x12@\n" +
	"\aGetUser\x12\x18.test.v1.GetUserResource\x1a\x11.test.v1.Response\"\b»\x01\x04read\x12G\n" +
	"\n" +
	"UpdateUser\x12\x1b.test.v1.UpdateUserResource\x1a\x11.test.v1.Response\"\t»\x01\x05write\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1b.test.v1.DeleteUserResource\x1a\x11.test.v1.Response\"\t»\x01\x05adminB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_mixed_service_proto_rawDescOnce sync.Once
	file_test_v1_mixed_service_proto_rawDescData []byte
)

func file_test_v1_mixed_service_proto_rawDescGZIP() []byte {
	file_test_v1_mixed_service_proto_rawDescOnce.Do(func() {
		file_test_v1_mixed_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_mixed_service_proto_rawDesc), len(file_test_v1_mixed_service_proto_rawDesc)))
	})
	return file_test_v1_mixed_service_proto_rawDescData
}

var file_test_v1_mixed_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_v1_mixed_service_proto_goTypes = []any{
	(*SimpleRequest)(nil),      // 0: test.v1.SimpleRequest
	(*GetUserResource)(nil),    // 1: test.v1.GetUserResource
	(*UpdateUserResource)(nil), // 2: test.v1.UpdateUserResource
	(*DeleteUserResource)(nil), // 3: test.v1.DeleteUserResource
	(*Response)(nil),           // 4: test.v1.Response
}
var file_test_v1_mixed_service_proto_depIdxs = []int32{
	0, // 0: test.v1.MixedService.GetPublicInfo:input_type -> test.v1.SimpleRequest
	1, // 1: test.v1.MixedService.GetUser:input_type -> test.v1.GetUserResource
	2, // 2: test.v1.MixedService.UpdateUser:input_type -> test.v1.UpdateUserResource
	3, // 3: test.v1.MixedService.DeleteUser:input_type -> test.v1.DeleteUserResource
	4, // 4: test.v1.MixedService.GetPublicInfo:output_type -> test.v1.Response
	4, // 5: test.v1.MixedService.GetUser:output_type -> test.v1.Response
	4, // 6: test.v1.MixedService.UpdateUser:output_type -> test.v1.Response
	4, // 7: test.v1.MixedService.DeleteUser:output_type -> test.v1.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_v1_mixed_service_proto_init() }
func file_test_v1_mixed_service_proto_init() {
	if File_test_v1_mixed_service_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_mixed_service_proto_rawDesc), len(file_test_v1_mixed_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_mixed_service_proto_goTypes,
		DependencyIndexes: file_test_v1_mixed_service_proto_depIdxs,
		MessageInfos:      file_test_v1_mixed_service_proto_msgTypes,
	}.Build()
	File_test_v1_mixed_service_proto = out.File
	file_test_v1_mixed_service_proto_goTypes = nil
	file_test_v1_mixed_service_proto_depIdxs = nil
}
