// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: test/v1/multiple_resources.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FolderId      string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_test_v1_multiple_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multiple_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_test_v1_multiple_resources_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_test_v1_multiple_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multiple_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_test_v1_multiple_resources_proto_rawDescGZIP(), []int{1}
}

func (x *Folder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Folder) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_test_v1_multiple_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multiple_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_test_v1_multiple_resources_proto_rawDescGZIP(), []int{2}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type MultiResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Document       *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Folder         *Folder                `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Workspace      *Workspace             `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	AdditionalDocs []*Document            `protobuf:"bytes,4,rep,name=additional_docs,json=additionalDocs,proto3" json:"additional_docs,omitempty"`
	FolderMap      map[string]*Folder     `protobuf:"bytes,5,rep,name=folder_map,json=folderMap,proto3" json:"folder_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultiResourceRequest) Reset() {
	*x = MultiResourceRequest{}
	mi := &file_test_v1_multiple_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiResourceRequest) ProtoMessage() {}

func (x *MultiResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multiple_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiResourceRequest.ProtoReflect.Descriptor instead.
func (*MultiResourceRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_multiple_resources_proto_rawDescGZIP(), []int{3}
}

func (x *MultiResourceRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *MultiResourceRequest) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

func (x *MultiResourceRequest) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *MultiResourceRequest) GetAdditionalDocs() []*Document {
	if x != nil {
		return x.AdditionalDocs
	}
	return nil
}

func (x *MultiResourceRequest) GetFolderMap() map[string]*Folder {
	if x != nil {
		return x.FolderMap
	}
	return nil
}

var File_test_v1_multiple_resources_proto protoreflect.FileDescriptor

const file_test_v1_multiple_resources_proto_rawDesc = "" +
	"\n" +
	" test/v1/multiple_resources.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"K\n" +
	"\bDocument\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId:\f»\x01\bDocument\"M\n" +
	"\x06Folder\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId:\n" +
	"»\x01\x06Folder\"S\n" +
	"\tWorkspace\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12!\n" +
	"\ttenant_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\btenantId:\r»\x01\tWorkspace\"\xf8\x02\n" +
	"\x14MultiResourceRequest\x12-\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.test.v1.DocumentR\bdocument\x12'\n" +
	"\x06folder\x18\x02 \x01(\v2\x0f.test.v1.FolderR\x06folder\x120\n" +
	"\tworkspace\x18\x03 \x01(\v2\x12.test.v1.WorkspaceR\tworkspace\x12:\n" +
	"\x0fadditional_docs\x18\x04 \x03(\v2\x11.test.v1.DocumentR\x0eadditionalDocs\x12K\n" +
	"\n" +
	"folder_map\x18\x05 \x03(\v2,.test.v1.MultiResourceRequest.FolderMapEntryR\tfolderMap\x1aM\n" +
	"\x0eFolderMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.test.v1.FolderR\x05value:\x028\x012p\n" +
	"\x14MultiResourceService\x12X\n" +
	"\x18ProcessMultipleResources\x12\x1d.test.v1.MultiResourceRequest\x1a\x11.test.v1.Response\"\n" +
	"»\x01\x06manageB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_multiple_resources_proto_rawDescOnce sync.Once
	file_test_v1_multiple_resources_proto_rawDescData []byte
)

func file_test_v1_multiple_resources_proto_rawDescGZIP() []byte {
	file_test_v1_multiple_resources_proto_rawDescOnce.Do(func() {
		file_test_v1_multiple_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_multiple_resources_proto_rawDesc), len(file_test_v1_multiple_resources_proto_rawDesc)))
	})
	return file_test_v1_multiple_resources_proto_rawDescData
}

var file_test_v1_multiple_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_v1_multiple_resources_proto_goTypes = []any{
	(*Document)(nil),             // 0: test.v1.Document
	(*Folder)(nil),               // 1: test.v1.Folder
	(*Workspace)(nil),            // 2: test.v1.Workspace
	(*MultiResourceRequest)(nil), // 3: test.v1.MultiResourceRequest
	nil,                          // 4: test.v1.MultiResourceRequest.FolderMapEntry
	(*Response)(nil),             // 5: test.v1.Response
}
var file_test_v1_multiple_resources_proto_depIdxs = []int32{
	0, // 0: test.v1.MultiResourceRequest.document:type_name -> test.v1.Document
	1, // 1: test.v1.MultiResourceRequest.folder:type_name -> test.v1.Folder
	2, // 2: test.v1.MultiResourceRequest.workspace:type_name -> test.v1.Workspace
	0, // 3: test.v1.MultiResourceRequest.additional_docs:type_name -> test.v1.Document
	4, // 4: test.v1.MultiResourceRequest.folder_map:type_name -> test.v1.MultiResourceRequest.FolderMapEntry
	1, // 5: test.v1.MultiResourceRequest.FolderMapEntry.value:type_name -> test.v1.Folder
	3, // 6: test.v1.MultiResourceService.ProcessMultipleResources:input_type -> test.v1.MultiResourceRequest
	5, // 7: test.v1.MultiResourceService.ProcessMultipleResources:output_type -> test.v1.Response
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_test_v1_multiple_resources_proto_init() }
func file_test_v1_multiple_resources_proto_init() {
	if File_test_v1_multiple_resources_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_multiple_resources_proto_rawDesc), len(file_test_v1_multiple_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_multiple_resources_proto_goTypes,
		DependencyIndexes: file_test_v1_multiple_resources_proto_depIdxs,
		MessageInfos:      file_test_v1_multiple_resources_proto_msgTypes,
	}.Build()
	File_test_v1_multiple_resources_proto = out.File
	file_test_v1_multiple_resources_proto_goTypes = nil
	file_test_v1_multiple_resources_proto_depIdxs = nil
}
