// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: test/v1/multi_service.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_test_v1_multi_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multi_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_test_v1_multi_service_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_test_v1_multi_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multi_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_test_v1_multi_service_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_test_v1_multi_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multi_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_test_v1_multi_service_proto_rawDescGZIP(), []int{2}
}

func (x *Settings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Settings) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type PublicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicInfo) Reset() {
	*x = PublicInfo{}
	mi := &file_test_v1_multi_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicInfo) ProtoMessage() {}

func (x *PublicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_multi_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicInfo.ProtoReflect.Descriptor instead.
func (*PublicInfo) Descriptor() ([]byte, []int) {
	return file_test_v1_multi_service_proto_rawDescGZIP(), []int{3}
}

func (x *PublicInfo) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_test_v1_multi_service_proto protoreflect.FileDescriptor

const file_test_v1_multi_service_proto_rawDesc = "" +
	"\n" +
	"\x1btest/v1/multi_service.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"I\n" +
	"\aAccount\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12\x1b\n" +
	"\x06org_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\x05orgId:\v»\x01\aAccount\"K\n" +
	"\aProfile\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId:\v»\x01\aProfile\"M\n" +
	"\bSettings\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId:\f»\x01\bSettings\" \n" +
	"\n" +
	"PublicInfo\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\x93\x01\n" +
	"\x0eAccountService\x12;\n" +
	"\n" +
	"GetAccount\x12\x10.test.v1.Account\x1a\x11.test.v1.Response\"\b»\x01\x04read\x12D\n" +
	"\x14GetPublicAccountInfo\x12\x13.test.v1.PublicInfo\x1a\x11.test.v1.Response\"\x04Ȼ\x01\x012M\n" +
	"\x0eProfileService\x12;\n" +
	"\n" +
	"GetProfile\x12\x10.test.v1.Profile\x1a\x11.test.v1.Response\"\b»\x01\x04read2P\n" +
	"\x0fSettingsService\x12=\n" +
	"\vGetSettings\x12\x11.test.v1.Settings\x1a\x11.test.v1.Response\"\b»\x01\x04readB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_multi_service_proto_rawDescOnce sync.Once
	file_test_v1_multi_service_proto_rawDescData []byte
)

func file_test_v1_multi_service_proto_rawDescGZIP() []byte {
	file_test_v1_multi_service_proto_rawDescOnce.Do(func() {
		file_test_v1_multi_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_multi_service_proto_rawDesc), len(file_test_v1_multi_service_proto_rawDesc)))
	})
	return file_test_v1_multi_service_proto_rawDescData
}

var file_test_v1_multi_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_v1_multi_service_proto_goTypes = []any{
	(*Account)(nil),    // 0: test.v1.Account
	(*Profile)(nil),    // 1: test.v1.Profile
	(*Settings)(nil),   // 2: test.v1.Settings
	(*PublicInfo)(nil), // 3: test.v1.PublicInfo
	(*Response)(nil),   // 4: test.v1.Response
}
var file_test_v1_multi_service_proto_depIdxs = []int32{
	0, // 0: test.v1.AccountService.GetAccount:input_type -> test.v1.Account
	3, // 1: test.v1.AccountService.GetPublicAccountInfo:input_type -> test.v1.PublicInfo
	1, // 2: test.v1.ProfileService.GetProfile:input_type -> test.v1.Profile
	2, // 3: test.v1.SettingsService.GetSettings:input_type -> test.v1.Settings
	4, // 4: test.v1.AccountService.GetAccount:output_type -> test.v1.Response
	4, // 5: test.v1.AccountService.GetPublicAccountInfo:output_type -> test.v1.Response
	4, // 6: test.v1.ProfileService.GetProfile:output_type -> test.v1.Response
	4, // 7: test.v1.SettingsService.GetSettings:output_type -> test.v1.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_v1_multi_service_proto_init() }
func file_test_v1_multi_service_proto_init() {
	if File_test_v1_multi_service_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_multi_service_proto_rawDesc), len(file_test_v1_multi_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_test_v1_multi_service_proto_goTypes,
		DependencyIndexes: file_test_v1_multi_service_proto_depIdxs,
		MessageInfos:      file_test_v1_multi_service_proto_msgTypes,
	}.Build()
	File_test_v1_multi_service_proto = out.File
	file_test_v1_multi_service_proto_goTypes = nil
	file_test_v1_multi_service_proto_depIdxs = nil
}
