// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/v1/nested_resources.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_test_v1_nested_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_nested_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_test_v1_nested_resources_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_test_v1_nested_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_nested_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_test_v1_nested_resources_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Projects      []*Project             `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedRequest) Reset() {
	*x = NestedRequest{}
	mi := &file_test_v1_nested_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedRequest) ProtoMessage() {}

func (x *NestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_nested_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedRequest.ProtoReflect.Descriptor instead.
func (*NestedRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_nested_resources_proto_rawDescGZIP(), []int{2}
}

func (x *NestedRequest) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *NestedRequest) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *NestedRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_test_v1_nested_resources_proto protoreflect.FileDescriptor

const file_test_v1_nested_resources_proto_rawDesc = "" +
	"\n" +
	"\x1etest/v1/nested_resources.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"Y\n" +
	"\fOrganization\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12!\n" +
	"\ttenant_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\btenantId:\x10»\x01\fOrganization\"@\n" +
	"\aProject\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name:\v»\x01\aProject\"\x94\x01\n" +
	"\rNestedRequest\x129\n" +
	"\forganization\x18\x01 \x01(\v2\x15.test.v1.OrganizationR\forganization\x12,\n" +
	"\bprojects\x18\x02 \x03(\v2\x10.test.v1.ProjectR\bprojects\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata2W\n" +
	"\rNestedService\x12F\n" +
	"\rProcessNested\x12\x16.test.v1.NestedRequest\x1a\x11.test.v1.Response\"\n" +
	"»\x01\x06manageB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_nested_resources_proto_rawDescOnce sync.Once
	file_test_v1_nested_resources_proto_rawDescData []byte
)

func file_test_v1_nested_resources_proto_rawDescGZIP() []byte {
	file_test_v1_nested_resources_proto_rawDescOnce.Do(func() {
		file_test_v1_nested_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_nested_resources_proto_rawDesc), len(file_test_v1_nested_resources_proto_rawDesc)))
	})
	return file_test_v1_nested_resources_proto_rawDescData
}

var file_test_v1_nested_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_v1_nested_resources_proto_goTypes = []any{
	(*Organization)(nil),  // 0: test.v1.Organization
	(*Project)(nil),       // 1: test.v1.Project
	(*NestedRequest)(nil), // 2: test.v1.NestedRequest
	(*Response)(nil),      // 3: test.v1.Response
}
var file_test_v1_nested_resources_proto_depIdxs = []int32{
	0, // 0: test.v1.NestedRequest.organization:type_name -> test.v1.Organization
	1, // 1: test.v1.NestedRequest.projects:type_name -> test.v1.Project
	2, // 2: test.v1.NestedService.ProcessNested:input_type -> test.v1.NestedRequest
	3, // 3: test.v1.NestedService.ProcessNested:output_type -> test.v1.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_v1_nested_resources_proto_init() }
func file_test_v1_nested_resources_proto_init() {
	if File_test_v1_nested_resources_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_nested_resources_proto_rawDesc), len(file_test_v1_nested_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_nested_resources_proto_goTypes,
		DependencyIndexes: file_test_v1_nested_resources_proto_depIdxs,
		MessageInfos:      file_test_v1_nested_resources_proto_msgTypes,
	}.Build()
	File_test_v1_nested_resources_proto = out.File
	file_test_v1_nested_resources_proto_goTypes = nil
	file_test_v1_nested_resources_proto_depIdxs = nil
}
