// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/v1/single.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *NestedResource        `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedResourceRequest) Reset() {
	*x = NestedResourceRequest{}
	mi := &file_test_v1_single_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedResourceRequest) ProtoMessage() {}

func (x *NestedResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_single_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedResourceRequest.ProtoReflect.Descriptor instead.
func (*NestedResourceRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_single_proto_rawDescGZIP(), []int{0}
}

func (x *NestedResourceRequest) GetResource() *NestedResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_test_v1_single_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_single_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_single_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourceWithIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceWithIdRequest) Reset() {
	*x = ResourceWithIdRequest{}
	mi := &file_test_v1_single_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWithIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWithIdRequest) ProtoMessage() {}

func (x *ResourceWithIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_single_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWithIdRequest.ProtoReflect.Descriptor instead.
func (*ResourceWithIdRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_single_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceWithIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceWithIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceWithIdRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

var File_test_v1_single_proto protoreflect.FileDescriptor

const file_test_v1_single_proto_rawDesc = "" +
	"\n" +
	"\x14test/v1/single.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"L\n" +
	"\x15NestedResourceRequest\x123\n" +
	"\bresource\x18\x01 \x01(\v2\x17.test.v1.NestedResourceR\bresource\"/\n" +
	"\x0fResourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:\b»\x01\x04Flat\"p\n" +
	"\x15ResourceWithIdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x02id\x18\x02 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12#\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tB\x04Ȼ\x01\x01R\tcompanyId:\b»\x01\x04Flat2\xdb\x01\n" +
	"\x06Single\x12?\n" +
	"\x04Flat\x12\x18.test.v1.ResourceRequest\x1a\x11.test.v1.Response\"\n" +
	"»\x01\x06create\x12I\n" +
	"\n" +
	"FlatWithId\x12\x1e.test.v1.ResourceWithIdRequest\x1a\x11.test.v1.Response\"\b»\x01\x04read\x12E\n" +
	"\x06Nested\x12\x1e.test.v1.NestedResourceRequest\x1a\x11.test.v1.Response\"\b»\x01\x04editB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_single_proto_rawDescOnce sync.Once
	file_test_v1_single_proto_rawDescData []byte
)

func file_test_v1_single_proto_rawDescGZIP() []byte {
	file_test_v1_single_proto_rawDescOnce.Do(func() {
		file_test_v1_single_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_single_proto_rawDesc), len(file_test_v1_single_proto_rawDesc)))
	})
	return file_test_v1_single_proto_rawDescData
}

var file_test_v1_single_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_v1_single_proto_goTypes = []any{
	(*NestedResourceRequest)(nil), // 0: test.v1.NestedResourceRequest
	(*ResourceRequest)(nil),       // 1: test.v1.ResourceRequest
	(*ResourceWithIdRequest)(nil), // 2: test.v1.ResourceWithIdRequest
	(*NestedResource)(nil),        // 3: test.v1.NestedResource
	(*Response)(nil),              // 4: test.v1.Response
}
var file_test_v1_single_proto_depIdxs = []int32{
	3, // 0: test.v1.NestedResourceRequest.resource:type_name -> test.v1.NestedResource
	1, // 1: test.v1.Single.Flat:input_type -> test.v1.ResourceRequest
	2, // 2: test.v1.Single.FlatWithId:input_type -> test.v1.ResourceWithIdRequest
	0, // 3: test.v1.Single.Nested:input_type -> test.v1.NestedResourceRequest
	4, // 4: test.v1.Single.Flat:output_type -> test.v1.Response
	4, // 5: test.v1.Single.FlatWithId:output_type -> test.v1.Response
	4, // 6: test.v1.Single.Nested:output_type -> test.v1.Response
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_v1_single_proto_init() }
func file_test_v1_single_proto_init() {
	if File_test_v1_single_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_single_proto_rawDesc), len(file_test_v1_single_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_single_proto_goTypes,
		DependencyIndexes: file_test_v1_single_proto_depIdxs,
		MessageInfos:      file_test_v1_single_proto_msgTypes,
	}.Build()
	File_test_v1_single_proto = out.File
	file_test_v1_single_proto_goTypes = nil
	file_test_v1_single_proto_depIdxs = nil
}
