// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: test/v1/single_resource.proto

package testv1

import (
	_ "github.com/nrf110/connectrpc-permify/gen/nrf110/permify/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_test_v1_single_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_single_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_single_resource_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_test_v1_single_resource_proto protoreflect.FileDescriptor

const file_test_v1_single_resource_proto_rawDesc = "" +
	"\n" +
	"\x1dtest/v1/single_resource.proto\x12\atest.v1\x1a\x1fnrf110/permify/v1/permify.proto\x1a\x14test/v1/common.proto\"l\n" +
	"\x11UpdateUserRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xc0\xbb\x01\x01R\x02id\x12#\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x04Ȼ\x01\x01R\tcompanyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name:\b»\x01\x04User2U\n" +
	"\vUserService\x12F\n" +
	"\n" +
	"UpdateUser\x12\x1a.test.v1.UpdateUserRequest\x1a\x11.test.v1.Response\"\t»\x01\x05writeB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_test_v1_single_resource_proto_rawDescOnce sync.Once
	file_test_v1_single_resource_proto_rawDescData []byte
)

func file_test_v1_single_resource_proto_rawDescGZIP() []byte {
	file_test_v1_single_resource_proto_rawDescOnce.Do(func() {
		file_test_v1_single_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_single_resource_proto_rawDesc), len(file_test_v1_single_resource_proto_rawDesc)))
	})
	return file_test_v1_single_resource_proto_rawDescData
}

var file_test_v1_single_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_v1_single_resource_proto_goTypes = []any{
	(*UpdateUserRequest)(nil), // 0: test.v1.UpdateUserRequest
	(*Response)(nil),          // 1: test.v1.Response
}
var file_test_v1_single_resource_proto_depIdxs = []int32{
	0, // 0: test.v1.UserService.UpdateUser:input_type -> test.v1.UpdateUserRequest
	1, // 1: test.v1.UserService.UpdateUser:output_type -> test.v1.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_v1_single_resource_proto_init() }
func file_test_v1_single_resource_proto_init() {
	if File_test_v1_single_resource_proto != nil {
		return
	}
	file_test_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_single_resource_proto_rawDesc), len(file_test_v1_single_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_single_resource_proto_goTypes,
		DependencyIndexes: file_test_v1_single_resource_proto_depIdxs,
		MessageInfos:      file_test_v1_single_resource_proto_msgTypes,
	}.Build()
	File_test_v1_single_resource_proto = out.File
	file_test_v1_single_resource_proto_goTypes = nil
	file_test_v1_single_resource_proto_depIdxs = nil
}
